const SUBJECTS=[
 {id:'math-drill',name:'計算ドリル',icon:'▦',color:'#2698ea',bg:'#dcf3ff'},
 {id:'kanji',name:'漢字',icon:'あ',color:'#e655a8',bg:'#ffe1f0'},
 {id:'arithmetic',name:'算数',icon:'✎',color:'#21bfa8',bg:'#e1f8ef'},
 {id:'science',name:'理科',icon:'♙',color:'#298ef0',bg:'#e4f3ff'},
 {id:'social',name:'社会',icon:'◎',color:'#288fdd',bg:'#dff5ff'},
 {id:'japanese',name:'国語',icon:'▤',color:'#8a51e7',bg:'#f0e8ff'},
 {id:'piano',name:'ピアノ',icon:'♫',color:'#e74da0',bg:'#ffe9f3'}
];
const DEFAULT_REWARDS=[['好きなデザートを選ぶ',10],['夕食メニュー決定権',20],['週末にやりたいことを選ぶ',30],['小さなごほうびを選ぶ',50]];
const KEY='akari-study-timer-v1',MODE_KEY='akari-device-mode',BACKUP_KEY='akari-study-backups-v1';
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const freshSubject=()=>({seconds:0,completed:false,pointAwarded:false,updatedAt:0,resetAt:0});
const freshDay=()=>({subjects:Object.fromEntries(SUBJECTS.map(s=>[s.id,freshSubject()])),bonusAwarded:false,bonusUpdatedAt:0,updatedAt:0});
const initialState=()=>({name:'あかり',points:0,pointsMeta:null,rewards:DEFAULT_REWARDS.map(x=>[...x]),days:{},exchanges:[],active:null,activeUpdatedAt:0,backups:[],revision:0});
let state=loadLocal(),activeTimer=null,tickHandle=null,pendingAction=null,cloudReady=false,cloudConnected=false,appStarted=false,deviceMode=localStorage.getItem(MODE_KEY),lastSyncAt=0,cloudWriteQueue=Promise.resolve();

function loadLocal(){try{return {...initialState(),...JSON.parse(localStorage.getItem(KEY))}}catch{return initialState()}}
function loadBackupStore(){try{return JSON.parse(localStorage.getItem(BACKUP_KEY))||[]}catch{return []}}
function uniqueBy(items,key){const seen=new Set();return items.filter(item=>{const value=key(item);if(seen.has(value))return false;seen.add(value);return true})}
function mergeSubject(a={},b={}){const at=Number(a.updatedAt)||0,bt=Number(b.updatedAt)||0,newer=bt>at?b:a,aReset=Number(a.resetAt)||0,bReset=Number(b.resetAt)||0;let seconds=Math.max(Number(a.seconds)||0,Number(b.seconds)||0);if(bReset>at&&bt>=at)seconds=Number(b.seconds)||0;else if(aReset>bt&&at>bt)seconds=Number(a.seconds)||0;return {seconds,completed:at===bt?Boolean(a.completed||b.completed):Boolean(newer.completed),pointAwarded:at===bt?Boolean(a.pointAwarded||b.pointAwarded||a.completed||b.completed):Boolean(newer.pointAwarded),updatedAt:Math.max(at,bt),resetAt:Math.max(aReset,bReset)}}
function mergeDay(a={},b={}){const subjects={};for(const subject of SUBJECTS)subjects[subject.id]=mergeSubject(a.subjects?.[subject.id],b.subjects?.[subject.id]);const aBonusAt=Number(a.bonusUpdatedAt)||0,bBonusAt=Number(b.bonusUpdatedAt)||0;return {subjects,bonusAwarded:aBonusAt===bBonusAt?Boolean(a.bonusAwarded||b.bonusAwarded):Boolean((bBonusAt>aBonusAt?b:a).bonusAwarded),bonusUpdatedAt:Math.max(aBonusAt,bBonusAt),updatedAt:Math.max(Number(a.updatedAt)||0,Number(b.updatedAt)||0)}}
function mergeStates(aRaw,bRaw){
  const a={...initialState(),...(aRaw||{})},b={...initialState(),...(bRaw||{})},merged={...initialState()};
  const dates=new Set([...Object.keys(a.days||{}),...Object.keys(b.days||{})]);merged.days={};for(const date of dates)merged.days[date]=mergeDay(a.days?.[date],b.days?.[date]);
  const aPointsAt=Number(a.pointsMeta?.at)||0,bPointsAt=Number(b.pointsMeta?.at)||0;if(aPointsAt||bPointsAt){const source=bPointsAt>aPointsAt?b:a;merged.points=Number(source.points)||0;merged.pointsMeta=source.pointsMeta||null}else merged.points=Math.max(Number(a.points)||0,Number(b.points)||0);
  merged.exchanges=uniqueBy([...(a.exchanges||[]),...(b.exchanges||[])],x=>x.at?`at:${x.at}`:`${x.date}|${x.name}|${x.points}`);
  merged.backups=uniqueBy([...(a.backups||[]),...(b.backups||[]),...loadBackupStore()],x=>x.id).sort((x,y)=>y.createdAt-x.createdAt).slice(0,40);
  const aActiveAt=Number(a.activeUpdatedAt)||Number(a.revision)||0,bActiveAt=Number(b.activeUpdatedAt)||Number(b.revision)||0,activeSource=bActiveAt>aActiveAt?b:a;merged.active=activeSource.active||null;merged.activeUpdatedAt=Math.max(aActiveAt,bActiveAt);
  const newer=(Number(b.revision)||0)>(Number(a.revision)||0)?b:a;merged.name=newer.name||a.name||b.name||'あかり';merged.rewards=newer.rewards||a.rewards||b.rewards||DEFAULT_REWARDS;
  merged.revision=Math.max(Number(a.revision)||0,Number(b.revision)||0);return merged;
}
function normalize(){const key=todayKey();state.days??={};state.days[key]??=freshDay();for(const [date,day] of Object.entries(state.days)){day.subjects??={};SUBJECTS.forEach(s=>{day.subjects[s.id]={...freshSubject(),...(day.subjects[s.id]||{})};if(typeof day.subjects[s.id].pointAwarded!=='boolean')day.subjects[s.id].pointAwarded=Boolean(day.subjects[s.id].completed)});day.updatedAt=Number(day.updatedAt)||0}state.rewards=(state.rewards||DEFAULT_REWARDS).map((r,i)=>Array.isArray(r)?r:[r.name||DEFAULT_REWARDS[i]?.[0],Number(r.points)||10]);state.exchanges??=[];state.backups=uniqueBy([...(state.backups||[]),...loadBackupStore()],x=>x.id).sort((a,b)=>b.createdAt-a.createdAt).slice(0,40);state.activeUpdatedAt=Number(state.activeUpdatedAt)||Number(state.revision)||0;if(state.active?.date===key&&!state.days[key].subjects[state.active.subject]?.completed)activeTimer=state.active;else{state.active=null;activeTimer=null}saveLocal()}
function saveLocal(){state.active=activeTimer;localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(BACKUP_KEY,JSON.stringify((state.backups||[]).slice(0,40)))}
function backupSignature(backup){return JSON.stringify([backup.date,backup.day,backup.points,backup.active])}
function recordBackup(reason='自動保存'){const date=todayKey(),backup={id:`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,createdAt:Date.now(),date,day:JSON.parse(JSON.stringify(state.days[date]||freshDay())),points:state.points,active:activeTimer?{...activeTimer}:null,reason};if(state.backups?.[0]&&backupSignature(state.backups[0])===backupSignature(backup))return;state.backups=[backup,...(state.backups||[])].slice(0,40)}
function snapshot(){return JSON.parse(JSON.stringify({...state,active:activeTimer}))}
function touchSubject(id){const now=Date.now();currentDay().subjects[id].updatedAt=now;currentDay().updatedAt=now}
function touchPoints(type){state.pointsMeta={at:Date.now(),type,id:`${Date.now()}-${Math.random().toString(36).slice(2,6)}`}}
function markSyncSuccess(){cloudConnected=true;lastSyncAt=Date.now();setSyncStatus('クラウドと同期済み')}
function applyRemote(payload){if(!payload){markSyncSuccess();return}const before=JSON.stringify(state),merged=mergeStates(payload,state);state=merged;normalize();if(JSON.stringify(state)!==before)renderAll();markSyncSuccess();if(activeTimer)startTicker()}
function save({cloud=true,reason='自動保存'}={}){recordBackup(reason);state.active=activeTimer;state.revision=Math.max(Date.now(),Number(state.revision)||0);saveLocal();if(cloud&&cloudReady&&window.AKARI_CLOUD?.currentUser()){setSyncStatus('同期中…');const outgoing=snapshot();cloudWriteQueue=cloudWriteQueue.catch(()=>{}).then(()=>window.AKARI_CLOUD.writeMerged?window.AKARI_CLOUD.writeMerged(outgoing,mergeStates):window.AKARI_CLOUD.write(outgoing)).then(merged=>{state=mergeStates(merged,state);normalize();markSyncSuccess();renderAll()}).catch(()=>{cloudConnected=false;setSyncStatus(navigator.onLine?'更新待ち':'オフライン・端末に保存済み')})}}
function currentDay(){return state.days[todayKey()]}
function elapsed(id,{parent=false}={}){const base=currentDay().subjects[id].seconds;if(activeTimer?.subject!==id)return base;const now=parent&&lastSyncAt?Math.min(Date.now(),lastSyncAt+15000):Date.now();return base+Math.max(0,Math.floor((now-activeTimer.startedAt)/1000))}
function format(sec){const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return [h,m,s].map(n=>String(n).padStart(2,'0')).join(':')}
function compactTime(sec){if(sec<60)return `${sec}秒`;const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);return h?`${h}時間${m?` ${m}分`:''}`:`${m}分`}
function commitActive(shouldSave=true){if(!activeTimer)return;const id=activeTimer.subject;currentDay().subjects[id].seconds=elapsed(id);touchSubject(id);activeTimer=null;state.activeUpdatedAt=Date.now();clearInterval(tickHandle);tickHandle=null;if(shouldSave)save({reason:'タイマーを一時停止'})}
function startTimer(id){if(deviceMode!=='daughter'||currentDay().subjects[id].completed)return;if(activeTimer&&activeTimer.subject!==id)commitActive(false);activeTimer={subject:id,startedAt:Date.now(),date:todayKey(),status:'running'};state.activeUpdatedAt=Date.now();touchSubject(id);save({reason:`${SUBJECTS.find(s=>s.id===id).name}を開始`});startTicker();renderAll();showToast(`${SUBJECTS.find(s=>s.id===id).name}をスタート！`)}
function pauseTimer(id){if(deviceMode!=='daughter'||activeTimer?.subject!==id)return;commitActive();renderAll();showToast('ここまでの時間を保存したよ')}
function toggleComplete(id){if(deviceMode!=='daughter')return;const item=currentDay().subjects[id];if(item.completed){ask('完了を取り消す？','時間はそのまま残して、もう一度タイマーを使えるようにします。',()=>{item.completed=false;touchSubject(id);if(currentDay().bonusAwarded){state.points=Math.max(0,state.points-3);currentDay().bonusAwarded=false;currentDay().bonusUpdatedAt=Date.now();touchPoints('完了ボーナス取消')}if(item.pointAwarded){state.points=Math.max(0,state.points-1);item.pointAwarded=false;touchPoints('完了取消')}save({reason:`${SUBJECTS.find(s=>s.id===id).name}の完了を取消`});renderAll()});return}if(activeTimer?.subject===id)commitActive(false);ask('このタスクを完了する？',`${SUBJECTS.find(s=>s.id===id).name}を今日の記録に保存します。`,()=>{if(item.completed)return;item.completed=true;touchSubject(id);if(!item.pointAwarded){state.points+=1;item.pointAwarded=true;touchPoints('科目完了')}if(Object.values(currentDay().subjects).every(x=>x.completed)&&!currentDay().bonusAwarded){state.points+=3;currentDay().bonusAwarded=true;currentDay().bonusUpdatedAt=Date.now();touchPoints('全科目完了');celebrate()}save({reason:`${SUBJECTS.find(s=>s.id===id).name}を完了`});renderAll();showToast('できた！ 1ポイントゲット ⭐')})}
function startTicker(){clearInterval(tickHandle);tickHandle=setInterval(()=>{if(activeTimer?.date!==todayKey()){commitActive();normalize();renderAll();return}renderTimers();renderParent()},1000)}
function renderTimers(){SUBJECTS.forEach(s=>{const el=document.querySelector(`[data-timer="${s.id}"]`);if(el)el.textContent=format(elapsed(s.id))});renderSummary()}
function renderHome(){const day=currentDay();document.querySelector('#taskList').innerHTML=SUBJECTS.map(s=>{const d=day.subjects[s.id],running=activeTimer?.subject===s.id;return `<div class="task-row ${d.completed?'completed':''}"><div class="subject"><span class="subject-icon" style="--icon-bg:${s.bg};--icon-color:${s.color}">${s.icon}</span><span class="subject-name">${s.name}</span></div><div class="timer" data-timer="${s.id}">${format(elapsed(s.id))}</div><div class="task-actions"><button class="action-btn start" data-action="start" data-id="${s.id}" ${running||d.completed?'disabled':''}><span>▶</span>スタート</button><button class="action-btn pause" data-action="pause" data-id="${s.id}" ${!running?'disabled':''}><span>Ⅱ</span>一時停止</button><button class="action-btn finish" data-action="finish" data-id="${s.id}"><span>${d.completed?'↶':'✓'}</span>${d.completed?'取り消す':'完了'}</button></div><span class="row-arrow">›</span></div>`}).join('');document.querySelector('#runningBadge').classList.toggle('hidden',!activeTimer);renderSummary();renderRewardsPreview()}
function renderSummary(){const items=Object.values(currentDay().subjects),total=SUBJECTS.reduce((n,s)=>n+elapsed(s.id),0),done=items.filter(x=>x.completed).length;document.querySelector('#totalHours').textContent=String(Math.floor(total/3600)).padStart(2,'0');document.querySelector('#totalMinutes').textContent=String(Math.floor(total%3600/60)).padStart(2,'0');document.querySelector('#missionCount').textContent=done;document.querySelector('#pointTotal').textContent=state.points;document.querySelector('#missionStars').innerHTML=SUBJECTS.map((_,i)=>`<span class="star ${i<done?'done':''}">☆</span>`).join('');document.querySelector('#missionMessage').textContent=done===7?'今日のミッション完了！ すごいね！':done?`あと ${7-done}こ。少しずつ進んでいるね♪`:'全部おわったら、すてきな一日になるよ♪';const msg=done===7?'ぜんぶできたね！\n今日はここまで♪':activeTimer?'集中できてるね！\nその調子だよ♪':done?'今日も一つ終わったね！\nえらいよ♪':'まだ始めてないよ！\nさあ、スタートしよう♪';document.querySelector('#encouragement').innerHTML=msg.replace('\n','<br>');const next=[...state.rewards].sort((a,b)=>a[1]-b[1]).find(r=>r[1]>state.points);document.querySelector('#nextReward').textContent=next?`つぎのごほうびまで あと ${next[1]-state.points} pt`:'好きなごほうびを選べるよ！'}
function renderRewardsPreview(){document.querySelector('#rewardPreview').innerHTML=state.rewards.map(r=>`<div class="reward-mini"><span>☆</span><b>${r[1]} pt</b><span>${escapeHtml(r[0])}</span><button class="use-button" data-reward="${r[1]}" data-name="${escapeHtml(r[0])}" ${state.points<r[1]?'disabled':''}>使う</button></div>`).join('')}
function renderRecords(){const entries=Object.entries(state.days).sort(([a],[b])=>b.localeCompare(a));document.querySelector('#recordsList').innerHTML=entries.length?entries.map(([date,day])=>{const total=Object.values(day.subjects).reduce((n,x)=>n+x.seconds,0),done=Object.values(day.subjects).filter(x=>x.completed).length;return `<article class="record-day"><div class="record-head"><time>${displayDate(date)}</time><span>${Math.floor(total/3600)}時間 ${Math.floor(total%3600/60)}分</span></div><div class="record-meta"><span>完了 ${done}/7</span><span>${SUBJECTS.filter(s=>day.subjects[s.id]?.seconds).map(s=>s.name).join('・')||'記録なし'}</span></div></article>`}).join(''):'<p class="empty">まだ記録がないよ。<br>タイマーを使うとここに残ります。</p>'}
function renderRewards(){document.querySelector('#rewardPointTotal').textContent=`${state.points} pt`;document.querySelector('#rewardsList').innerHTML=state.rewards.map(r=>`<div class="reward-row"><span class="reward-star">☆</span><b>${r[1]} pt</b><div><strong>${escapeHtml(r[0])}</strong><br><small>${state.points>=r[1]?'交換できるよ！':`あと ${r[1]-state.points} pt`}</small></div><button class="use-button" data-reward="${r[1]}" data-name="${escapeHtml(r[0])}" ${state.points<r[1]?'disabled':''}>使う</button></div>`).join('');document.querySelector('#exchangeHistory').innerHTML=state.exchanges.length?state.exchanges.slice().reverse().map(x=>`<div class="history-item"><span>${escapeHtml(x.name)}</span><small>${displayDate(x.date)}・${x.points} pt</small></div>`).join(''):'<p class="empty">まだ交換していないよ</p>'}
function renderGraph(){const dates=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}),values=dates.map(k=>Object.values(state.days[k]?.subjects||{}).reduce((n,x)=>n+x.seconds,0)),max=Math.max(1800,...values);document.querySelector('#weekChart').innerHTML=dates.map((d,i)=>`<div class="bar-column"><span class="bar-value">${Math.round(values[i]/60)}分</span><div class="bar" style="height:${Math.max(2,values[i]/max*88)}%"></div><span>${new Date(d+'T00:00:00').toLocaleDateString('ja-JP',{weekday:'short'})}</span></div>`).join('');const totals=SUBJECTS.map(s=>[s,Object.values(state.days).reduce((n,d)=>n+(d.subjects[s.id]?.seconds||0),0)]),smax=Math.max(1,...totals.map(x=>x[1]));document.querySelector('#subjectChart').innerHTML=totals.map(([s,v])=>`<div class="subject-bar-row"><span>${s.icon} ${s.name}</span><div class="subject-bar-track"><div class="subject-bar-fill" style="width:${v/smax*100}%;--bar-color:${s.color}"></div></div><b>${Math.round(v/60)}分</b></div>`).join('')}
function renderParent(){if(!currentDay())return;const done=Object.values(currentDay().subjects).filter(x=>x.completed).length,total=SUBJECTS.reduce((n,s)=>n+elapsed(s.id,{parent:true}),0);document.querySelector('#parentDate').textContent=displayDate(todayKey()).replace(/（.）/,'');document.querySelector('#parentGreeting').textContent=`${state.name}さんの今日のがんばり`;document.querySelector('#parentSubjectList').innerHTML=SUBJECTS.map(s=>{const d=currentDay().subjects[s.id],running=activeTimer?.subject===s.id,status=running?'取り組み中':d.completed?'完了':'まだ';return `<div class="parent-subject ${running?'running':d.completed?'completed':''}"><span class="parent-subject-icon">${running?'▶':d.completed?'✓':'○'}</span><div class="parent-subject-info"><b>${s.name}</b><small>${status}</small></div><span class="parent-subject-time">${running?format(elapsed(s.id,{parent:true})):compactTime(d.seconds)}</span></div>`}).join('');document.querySelector('#parentRunningBadge').classList.toggle('hidden',!activeTimer);document.querySelector('#parentMission').textContent=`${done} / 7`;document.querySelector('#parentTotal').textContent=compactTime(total);document.querySelector('#parentPoints').textContent=`${state.points} pt`;document.querySelector('#parentExchangeHistory').innerHTML=state.exchanges.length?state.exchanges.slice().reverse().map(x=>`<div class="parent-exchange-item"><span class="parent-exchange-icon">🎁</span><div><b>${escapeHtml(x.name)}</b><small>${displayDate(x.date).replace(/（.）/,'')} に申請</small></div><strong>−${x.points} pt</strong></div>`).join(''):'<p class="empty parent-empty">まだごほうび申請はありません</p>'}
function renderBackups(){const el=document.querySelector('#backupList');if(!el)return;el.innerHTML=(state.backups||[]).slice(0,12).map(b=>{const done=Object.values(b.day?.subjects||{}).filter(x=>x.completed).length,total=Object.values(b.day?.subjects||{}).reduce((n,x)=>n+(x.seconds||0),0);return `<div class="backup-item"><div><b>${new Date(b.createdAt).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}</b><small>${escapeHtml(b.reason||'自動保存')}・完了 ${done}/7・${compactTime(total)}</small></div><button type="button" class="secondary-button" data-restore="${b.id}">復元</button></div>`}).join('')||'<p class="empty">まだ復元履歴はありません</p>'}
function renderSettings(){document.querySelector('#nameInput').value=state.name;document.querySelector('#rewardSettings').innerHTML=state.rewards.map((r,i)=>`<div class="reward-setting"><label>ごほうび<input data-reward-name="${i}" value="${escapeHtml(r[0])}" maxlength="30"></label><label>ポイント<input data-reward-points="${i}" type="number" min="1" max="999" value="${r[1]}"></label></div>`).join('');const user=window.AKARI_CLOUD?.currentUser();document.querySelector('#accountLabel').textContent=user?.email||'未接続';document.querySelector('#connectionDot').classList.toggle('online',cloudConnected);renderBackups()}
function saveSettings(){state.name=document.querySelector('#nameInput').value.trim()||'あかり';state.rewards=state.rewards.map((_,i)=>[document.querySelector(`[data-reward-name="${i}"]`).value.trim()||'ごほうび',Math.max(1,Number(document.querySelector(`[data-reward-points="${i}"]`).value)||1)]);save({reason:'設定を変更'});renderAll();showToast('設定を保存したよ')}
function exchange(name,points){if(deviceMode==='parent')return;ask('このごほうびを申請する？',`${points}pt使って「${name}」を保護者に申請します。`,()=>{if(state.points<points)return;state.points-=points;touchPoints('ごほうび申請');state.exchanges.push({name,points,date:todayKey(),at:Date.now(),status:'requested'});save({reason:'ごほうびを申請'});renderAll();showToast('保護者にごほうびを申請したよ 🎁')})}
function navigate(name){document.querySelectorAll('#daughterApp .view').forEach(x=>x.classList.remove('active'));document.querySelector(`#${name}View`).classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));if(name==='records')renderRecords();if(name==='rewards')renderRewards();if(name==='graph')renderGraph();scrollTo({top:0,behavior:'smooth'})}
function ask(title,text,action){pendingAction=action;document.querySelector('#confirmTitle').textContent=title;document.querySelector('#confirmText').textContent=text;document.querySelector('#confirmDialog').showModal()}
function showToast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function celebrate(){document.body.animate([{filter:'brightness(1)'},{filter:'brightness(1.08)'},{filter:'brightness(1)'}],{duration:800});showToast('ミッション完了ボーナス +3pt！ ✨')}
function displayDate(key){const d=new Date(key+'T00:00:00');return `${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日（${'日月火水木金土'[d.getDay()]}）`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderHeader(){const h=new Date().getHours();document.querySelector('#greeting').textContent=`${h<11?'おはよう':h<17?'こんにちは':'こんばんは'}、${state.name}！`;document.querySelector('#todayDate').textContent=displayDate(todayKey())}
function renderAll(){renderHeader();renderHome();renderRecords();renderRewards();renderGraph();renderParent();applyMode()}
function applyMode(){document.querySelector('#daughterApp').classList.toggle('hidden',deviceMode==='parent');document.querySelector('#parentApp').classList.toggle('hidden',deviceMode!=='parent')}
function setSyncStatus(text){const status=document.querySelector('#parentSyncStatus'),label=document.querySelector('#connectionLabel'),last=document.querySelector('#parentLastSync');if(status)status.textContent=text;if(label)label.textContent=text;if(last)last.textContent=lastSyncAt?`最終同期：${new Date(lastSyncAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'最終同期：--:--'}
function chooseMode(){const dialog=document.querySelector('#modeDialog');dialog.showModal();dialog.addEventListener('close',()=>{if(['daughter','parent'].includes(dialog.returnValue)){deviceMode=dialog.returnValue;localStorage.setItem(MODE_KEY,deviceMode);applyMode();renderAll()}else if(!deviceMode)setTimeout(chooseMode,100)},{once:true})}
function startApp(){if(appStarted)return;appStarted=true;normalize();renderAll();if(activeTimer)startTicker();if(!deviceMode)chooseMode();document.querySelector('#authScreen').classList.add('hidden')}
async function handleAuthenticated(user){cloudReady=true;setSyncStatus('クラウドに接続しています…');let shouldUpload=false;try{const remote=await window.AKARI_CLOUD.read(),merged=mergeStates(remote,state);shouldUpload=JSON.stringify(merged)!==JSON.stringify(remote);state=merged;normalize();markSyncSuccess()}catch{cloudConnected=false;normalize();shouldUpload=true;setSyncStatus(navigator.onLine?'更新待ち':'オフライン・端末に保存済み')}window.AKARI_CLOUD.subscribe((payload,meta)=>{if(meta.pending)return;applyRemote(payload)});startApp();document.querySelector('#accountLabel').textContent=user.email;if(shouldUpload||!state.backups?.length)save({reason:'起動時バックアップ'})}
function showAuth(){document.querySelector('#authScreen').classList.remove('hidden');document.querySelector('#daughterApp').classList.add('hidden');document.querySelector('#parentApp').classList.add('hidden')}
function authMessage(error){const map={'auth/invalid-credential':'メールアドレスまたはパスワードが違います。','auth/email-already-in-use':'このメールアドレスは登録済みです。「ログイン」を押してください。','auth/weak-password':'パスワードは6文字以上にしてください。','auth/invalid-email':'メールアドレスを確認してください。'};return map[error.code]||'接続できませんでした。通信状態を確認してください。'}
async function submitAuth(register=false){const email=document.querySelector('#emailInput').value.trim(),password=document.querySelector('#passwordInput').value,error=document.querySelector('#authError');error.textContent='';if(!email||password.length<6){error.textContent='メールアドレスと6文字以上のパスワードを入力してください。';return}try{if(register){if(!confirm('このメールアドレスで家族アカウントを作りますか？'))return;await window.AKARI_CLOUD.register(email,password)}else await window.AKARI_CLOUD.login(email,password)}catch(e){error.textContent=authMessage(e)}}
function cloudBoot(){window.AKARI_CLOUD.ready.then(user=>user?handleAuthenticated({uid:user.uid,email:user.email}):showAuth())}
async function manualRefresh(){const button=document.querySelector('#parentRefreshButton');if(button)button.disabled=true;setSyncStatus('更新中…');try{const payload=await window.AKARI_CLOUD.refresh();applyRemote(payload);renderAll();showToast('最新の状態に更新しました')}catch{cloudConnected=false;setSyncStatus(navigator.onLine?'更新待ち':'オフライン')}finally{if(button)button.disabled=false}}
function restoreBackup(id){const backup=(state.backups||[]).find(x=>x.id===id);if(!backup)return;ask('この状態に復元する？',`${new Date(backup.createdAt).toLocaleString('ja-JP')}の記録に戻します。現在の状態も復元履歴に残ります。`,()=>{recordBackup('復元前の状態');const now=Date.now(),day=JSON.parse(JSON.stringify(backup.day));for(const subject of SUBJECTS){day.subjects[subject.id].updatedAt=now;day.subjects[subject.id].resetAt=now}day.updatedAt=now;day.bonusUpdatedAt=now;state.days[backup.date]=day;state.points=backup.points;touchPoints('履歴から復元');activeTimer=backup.date===todayKey()?backup.active:null;state.activeUpdatedAt=now;save({reason:'履歴から復元'});document.querySelector('#settingsDialog').close();renderAll();showToast('記録を復元しました')})}

document.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action){const {action:a,id}=action.dataset;if(a==='start')startTimer(id);if(a==='pause')pauseTimer(id);if(a==='finish')toggleComplete(id)}const nav=e.target.closest('[data-nav]');if(nav)navigate(nav.dataset.nav);const reward=e.target.closest('[data-reward]');if(reward&&!reward.disabled)exchange(reward.dataset.name,Number(reward.dataset.reward));const restore=e.target.closest('[data-restore]');if(restore)restoreBackup(restore.dataset.restore)});
document.querySelector('#authForm').addEventListener('submit',e=>{e.preventDefault();submitAuth(false)});document.querySelector('#createAccountButton').addEventListener('click',()=>submitAuth(true));
function openSettings(){renderSettings();document.querySelector('#settingsDialog').showModal()}document.querySelector('#settingsButton').addEventListener('click',openSettings);document.querySelector('#parentSettingsButton').addEventListener('click',openSettings);document.querySelector('#parentRefreshButton').addEventListener('click',manualRefresh);document.querySelector('#saveSettings').addEventListener('click',saveSettings);document.querySelector('#switchModeButton').addEventListener('click',()=>{document.querySelector('#settingsDialog').close();deviceMode=null;localStorage.removeItem(MODE_KEY);chooseMode()});document.querySelector('#logoutButton').addEventListener('click',async()=>{document.querySelector('#settingsDialog').close();await window.AKARI_CLOUD.logout();location.reload()});document.querySelector('#confirmAction').addEventListener('click',()=>{pendingAction?.();pendingAction=null});document.querySelector('#confirmDialog').addEventListener('close',()=>{if(document.querySelector('#confirmDialog').returnValue==='cancel')pendingAction=null});document.addEventListener('visibilitychange',()=>{if(document.hidden)saveLocal();else{renderAll();setSyncStatus('更新中…')}});window.addEventListener('beforeunload',saveLocal);window.addEventListener('akari-sync-error',()=>{cloudConnected=false;setSyncStatus(navigator.onLine?'更新待ち':'オフライン・端末に保存済み')});window.addEventListener('akari-offline',()=>{cloudConnected=false;setSyncStatus('オフライン・端末に保存済み')});window.addEventListener('akari-auth',e=>{if(e.detail.user&&!appStarted)handleAuthenticated(e.detail.user)});
setInterval(()=>{if(!lastSyncAt)return;if(!navigator.onLine){cloudConnected=false;setSyncStatus('オフライン')}else if(Date.now()-lastSyncAt>10000){cloudConnected=false;setSyncStatus('更新待ち')}else setSyncStatus('クラウドと同期済み')},3000);
if(window.AKARI_CLOUD)cloudBoot();else window.addEventListener('akari-cloud-ready',cloudBoot,{once:true});
setTimeout(()=>{if(!appStarted&&!window.AKARI_CLOUD){showAuth();document.querySelector('#authError').textContent='クラウド接続を読み込めませんでした。通信状態を確認して、ページを再読み込みしてください。'}},8000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
