const SUBJECTS=[
 {id:'math-drill',name:'計算ドリル',icon:'▦',color:'#2698ea',bg:'#dcf3ff'},
 {id:'kanji',name:'漢字',icon:'あ',color:'#e655a8',bg:'#ffe1f0'},
 {id:'arithmetic',name:'算数',icon:'✎',color:'#21bfa8',bg:'#e1f8ef'},
 {id:'science',name:'理科',icon:'♙',color:'#298ef0',bg:'#e4f3ff'},
 {id:'social',name:'社会',icon:'◎',color:'#288fdd',bg:'#dff5ff'},
 {id:'japanese',name:'国語',icon:'▤',color:'#8a51e7',bg:'#f0e8ff'},
 {id:'piano',name:'ピアノ',icon:'♫',color:'#e74da0',bg:'#ffe9f3'}
];
const DEFAULT_REWARDS=[['好きなデザートを選ぶ',10],['夕食メニュー決定権',20],['週末にやりたいことを選ぶ',30],['小さなごほうびを選ぶ',50]];
const KEY='akari-study-timer-v1',MODE_KEY='akari-device-mode';
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const freshDay=()=>({subjects:Object.fromEntries(SUBJECTS.map(s=>[s.id,{seconds:0,completed:false}])),bonusAwarded:false});
const initialState=()=>({name:'あかり',points:0,rewards:DEFAULT_REWARDS.map(x=>[...x]),days:{},exchanges:[],active:null,revision:0});
let state=loadLocal(),activeTimer=null,tickHandle=null,pendingAction=null,cloudReady=false,cloudConnected=false,appStarted=false,ignoreRemote=false,deviceMode=localStorage.getItem(MODE_KEY);

function loadLocal(){try{return {...initialState(),...JSON.parse(localStorage.getItem(KEY))}}catch{return initialState()}}
function mergeForMigration(remote,local){const merged={...initialState(),...(remote||{})};merged.days={...(remote?.days||{})};for(const [date,localDay] of Object.entries(local.days||{})){const remoteDay=merged.days[date]||freshDay();const subjects={...remoteDay.subjects};for(const subject of SUBJECTS){const a=subjects[subject.id]||{seconds:0,completed:false},b=localDay.subjects?.[subject.id]||{seconds:0,completed:false};subjects[subject.id]={seconds:Math.max(a.seconds||0,b.seconds||0),completed:Boolean(a.completed||b.completed)}}merged.days[date]={...remoteDay,...localDay,subjects,bonusAwarded:Boolean(remoteDay.bonusAwarded||localDay.bonusAwarded)}}merged.points=Math.max(remote?.points||0,local.points||0);const exchanges=[...(remote?.exchanges||[]),...(local.exchanges||[])];merged.exchanges=exchanges.filter((x,i,a)=>a.findIndex(y=>(y.at&&y.at===x.at)||(!y.at&&y.date===x.date&&y.name===x.name&&y.points===x.points))===i);if(JSON.stringify(local.rewards)!==JSON.stringify(DEFAULT_REWARDS))merged.rewards=local.rewards;if(local.name&&local.name!=='あかり')merged.name=local.name;const candidates=[remote?.active,local.active].filter(x=>x?.date===todayKey());merged.active=candidates.sort((a,b)=>(b.startedAt||0)-(a.startedAt||0))[0]||null;merged.revision=Date.now();return merged}
function normalize(){const key=todayKey();state.days??={};state.days[key]??=freshDay();SUBJECTS.forEach(s=>state.days[key].subjects[s.id]??={seconds:0,completed:false});state.rewards=(state.rewards||DEFAULT_REWARDS).map((r,i)=>Array.isArray(r)?r:[r.name||DEFAULT_REWARDS[i]?.[0],Number(r.points)||10]);state.exchanges??=[];if(state.active?.date===key&&!state.days[key].subjects[state.active.subject]?.completed)activeTimer=state.active;else{state.active=null;activeTimer=null}saveLocal()}
function saveLocal(){state.active=activeTimer;localStorage.setItem(KEY,JSON.stringify(state))}
function snapshot(){return JSON.parse(JSON.stringify({...state,active:activeTimer,revision:Date.now()}))}
function save({cloud=true}={}){state.active=activeTimer;state.revision=Date.now();saveLocal();if(cloud&&cloudReady&&window.AKARI_CLOUD?.currentUser()){setSyncStatus('同期中…');window.AKARI_CLOUD.write(snapshot()).then(()=>{cloudConnected=true;setSyncStatus('クラウドと同期済み')}).catch(()=>{cloudConnected=false;setSyncStatus('オフライン・端末に保存済み')})}}
function currentDay(){return state.days[todayKey()]}
function elapsed(id){const base=currentDay().subjects[id].seconds;return activeTimer?.subject===id?base+Math.max(0,Math.floor((Date.now()-activeTimer.startedAt)/1000)):base}
function format(sec){const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return [h,m,s].map(n=>String(n).padStart(2,'0')).join(':')}
function compactTime(sec){if(sec<60)return `${sec}秒`;const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);return h?`${h}時間${m?` ${m}分`:''}`:`${m}分`}
function commitActive(shouldSave=true){if(!activeTimer)return;currentDay().subjects[activeTimer.subject].seconds=elapsed(activeTimer.subject);activeTimer=null;clearInterval(tickHandle);tickHandle=null;if(shouldSave)save()}
function startTimer(id){if(deviceMode!=='daughter'||currentDay().subjects[id].completed)return;if(activeTimer&&activeTimer.subject!==id)commitActive(false);activeTimer={subject:id,startedAt:Date.now(),date:todayKey(),status:'running'};save();startTicker();renderAll();showToast(`${SUBJECTS.find(s=>s.id===id).name}をスタート！`)}
function pauseTimer(id){if(deviceMode!=='daughter'||activeTimer?.subject!==id)return;commitActive();renderAll();showToast('ここまでの時間を保存したよ')}
function toggleComplete(id){if(deviceMode!=='daughter')return;const item=currentDay().subjects[id];if(item.completed){ask('完了を取り消す？','時間はそのまま残して、もう一度タイマーを使えるようにします。',()=>{item.completed=false;currentDay().bonusAwarded=false;state.points=Math.max(0,state.points-1);save();renderAll()});return}if(activeTimer?.subject===id)commitActive(false);ask('このタスクを完了する？',`${SUBJECTS.find(s=>s.id===id).name}を今日の記録に保存します。`,()=>{item.completed=true;state.points+=1;if(Object.values(currentDay().subjects).every(x=>x.completed)&&!currentDay().bonusAwarded){state.points+=3;currentDay().bonusAwarded=true;celebrate()}save();renderAll();showToast('できた！ 1ポイントゲット ⭐')})}
function startTicker(){clearInterval(tickHandle);tickHandle=setInterval(()=>{if(activeTimer?.date!==todayKey()){commitActive();normalize();renderAll();return}renderTimers();renderParent()},1000)}
function renderTimers(){SUBJECTS.forEach(s=>{const el=document.querySelector(`[data-timer="${s.id}"]`);if(el)el.textContent=format(elapsed(s.id))});renderSummary()}
function renderHome(){const day=currentDay();document.querySelector('#taskList').innerHTML=SUBJECTS.map(s=>{const d=day.subjects[s.id],running=activeTimer?.subject===s.id;return `<div class="task-row ${d.completed?'completed':''}"><div class="subject"><span class="subject-icon" style="--icon-bg:${s.bg};--icon-color:${s.color}">${s.icon}</span><span class="subject-name">${s.name}</span></div><div class="timer" data-timer="${s.id}">${format(elapsed(s.id))}</div><div class="task-actions"><button class="action-btn start" data-action="start" data-id="${s.id}" ${running||d.completed?'disabled':''}><span>▶</span>スタート</button><button class="action-btn pause" data-action="pause" data-id="${s.id}" ${!running?'disabled':''}><span>Ⅱ</span>一時停止</button><button class="action-btn finish" data-action="finish" data-id="${s.id}"><span>${d.completed?'↶':'✓'}</span>${d.completed?'取り消す':'完了'}</button></div><span class="row-arrow">›</span></div>`}).join('');document.querySelector('#runningBadge').classList.toggle('hidden',!activeTimer);renderSummary();renderRewardsPreview()}
function renderSummary(){const items=Object.values(currentDay().subjects),total=SUBJECTS.reduce((n,s)=>n+elapsed(s.id),0),done=items.filter(x=>x.completed).length;document.querySelector('#totalHours').textContent=String(Math.floor(total/3600)).padStart(2,'0');document.querySelector('#totalMinutes').textContent=String(Math.floor(total%3600/60)).padStart(2,'0');document.querySelector('#missionCount').textContent=done;document.querySelector('#pointTotal').textContent=state.points;document.querySelector('#missionStars').innerHTML=SUBJECTS.map((_,i)=>`<span class="star ${i<done?'done':''}">☆</span>`).join('');document.querySelector('#missionMessage').textContent=done===7?'今日のミッション完了！ すごいね！':done?`あと ${7-done}こ。少しずつ進んでいるね♪`:'全部おわったら、すてきな一日になるよ♪';const msg=done===7?'ぜんぶできたね！\n今日はここまで♪':activeTimer?'集中できてるね！\nその調子だよ♪':done?'今日も一つ終わったね！\nえらいよ♪':'まだ始めてないよ！\nさあ、スタートしよう♪';document.querySelector('#encouragement').innerHTML=msg.replace('\n','<br>');const next=[...state.rewards].sort((a,b)=>a[1]-b[1]).find(r=>r[1]>state.points);document.querySelector('#nextReward').textContent=next?`つぎのごほうびまで あと ${next[1]-state.points} pt`:'好きなごほうびを選べるよ！'}
function renderRewardsPreview(){document.querySelector('#rewardPreview').innerHTML=state.rewards.map(r=>`<div class="reward-mini"><span>☆</span><b>${r[1]} pt</b><span>${escapeHtml(r[0])}</span><button class="use-button" data-reward="${r[1]}" data-name="${escapeHtml(r[0])}" ${state.points<r[1]?'disabled':''}>使う</button></div>`).join('')}
function renderRecords(){const entries=Object.entries(state.days).sort(([a],[b])=>b.localeCompare(a));document.querySelector('#recordsList').innerHTML=entries.length?entries.map(([date,day])=>{const total=Object.values(day.subjects).reduce((n,x)=>n+x.seconds,0),done=Object.values(day.subjects).filter(x=>x.completed).length;return `<article class="record-day"><div class="record-head"><time>${displayDate(date)}</time><span>${Math.floor(total/3600)}時間 ${Math.floor(total%3600/60)}分</span></div><div class="record-meta"><span>完了 ${done}/7</span><span>${SUBJECTS.filter(s=>day.subjects[s.id]?.seconds).map(s=>s.name).join('・')||'記録なし'}</span></div></article>`}).join(''):'<p class="empty">まだ記録がないよ。<br>タイマーを使うとここに残ります。</p>'}
function renderRewards(){document.querySelector('#rewardPointTotal').textContent=`${state.points} pt`;document.querySelector('#rewardsList').innerHTML=state.rewards.map(r=>`<div class="reward-row"><span class="reward-star">☆</span><b>${r[1]} pt</b><div><strong>${escapeHtml(r[0])}</strong><br><small>${state.points>=r[1]?'交換できるよ！':`あと ${r[1]-state.points} pt`}</small></div><button class="use-button" data-reward="${r[1]}" data-name="${escapeHtml(r[0])}" ${state.points<r[1]?'disabled':''}>使う</button></div>`).join('');document.querySelector('#exchangeHistory').innerHTML=state.exchanges.length?state.exchanges.slice().reverse().map(x=>`<div class="history-item"><span>${escapeHtml(x.name)}</span><small>${displayDate(x.date)}・${x.points} pt</small></div>`).join(''):'<p class="empty">まだ交換していないよ</p>'}
function renderGraph(){const dates=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}),values=dates.map(k=>Object.values(state.days[k]?.subjects||{}).reduce((n,x)=>n+x.seconds,0)),max=Math.max(1800,...values);document.querySelector('#weekChart').innerHTML=dates.map((d,i)=>`<div class="bar-column"><span class="bar-value">${Math.round(values[i]/60)}分</span><div class="bar" style="height:${Math.max(2,values[i]/max*88)}%"></div><span>${new Date(d+'T00:00:00').toLocaleDateString('ja-JP',{weekday:'short'})}</span></div>`).join('');const totals=SUBJECTS.map(s=>[s,Object.values(state.days).reduce((n,d)=>n+(d.subjects[s.id]?.seconds||0),0)]),smax=Math.max(1,...totals.map(x=>x[1]));document.querySelector('#subjectChart').innerHTML=totals.map(([s,v])=>`<div class="subject-bar-row"><span>${s.icon} ${s.name}</span><div class="subject-bar-track"><div class="subject-bar-fill" style="width:${v/smax*100}%;--bar-color:${s.color}"></div></div><b>${Math.round(v/60)}分</b></div>`).join('')}
function renderParent(){if(!currentDay())return;const done=Object.values(currentDay().subjects).filter(x=>x.completed).length,total=SUBJECTS.reduce((n,s)=>n+elapsed(s.id),0);document.querySelector('#parentDate').textContent=displayDate(todayKey()).replace(/（.）/,'');document.querySelector('#parentGreeting').textContent=`${state.name}さんの今日のがんばり`;document.querySelector('#parentSubjectList').innerHTML=SUBJECTS.map(s=>{const d=currentDay().subjects[s.id],running=activeTimer?.subject===s.id,status=running?'取り組み中':d.completed?'完了':'まだ';return `<div class="parent-subject ${running?'running':d.completed?'completed':''}"><span class="parent-subject-icon">${running?'▶':d.completed?'✓':'○'}</span><div class="parent-subject-info"><b>${s.name}</b><small>${status}</small></div><span class="parent-subject-time">${running?format(elapsed(s.id)):compactTime(d.seconds)}</span></div>`}).join('');document.querySelector('#parentRunningBadge').classList.toggle('hidden',!activeTimer);document.querySelector('#parentMission').textContent=`${done} / 7`;document.querySelector('#parentTotal').textContent=compactTime(total);document.querySelector('#parentPoints').textContent=`${state.points} pt`;document.querySelector('#parentExchangeHistory').innerHTML=state.exchanges.length?state.exchanges.slice().reverse().map(x=>`<div class="parent-exchange-item"><span class="parent-exchange-icon">🎁</span><div><b>${escapeHtml(x.name)}</b><small>${displayDate(x.date).replace(/（.）/,'')} に申請</small></div><strong>−${x.points} pt</strong></div>`).join(''):'<p class="empty parent-empty">まだごほうび申請はありません</p>'}
function renderSettings(){document.querySelector('#nameInput').value=state.name;document.querySelector('#rewardSettings').innerHTML=state.rewards.map((r,i)=>`<div class="reward-setting"><label>ごほうび<input data-reward-name="${i}" value="${escapeHtml(r[0])}" maxlength="30"></label><label>ポイント<input data-reward-points="${i}" type="number" min="1" max="999" value="${r[1]}"></label></div>`).join('');const user=window.AKARI_CLOUD?.currentUser();document.querySelector('#accountLabel').textContent=user?.email||'未接続';document.querySelector('#connectionDot').classList.toggle('online',cloudConnected)}
function saveSettings(){state.name=document.querySelector('#nameInput').value.trim()||'あかり';state.rewards=state.rewards.map((_,i)=>[document.querySelector(`[data-reward-name="${i}"]`).value.trim()||'ごほうび',Math.max(1,Number(document.querySelector(`[data-reward-points="${i}"]`).value)||1)]);save();renderAll();showToast('設定を保存したよ')}
function exchange(name,points){if(deviceMode==='parent')return;ask('このごほうびを申請する？',`${points}pt使って「${name}」を保護者に申請します。`,()=>{if(state.points<points)return;state.points-=points;state.exchanges.push({name,points,date:todayKey(),at:Date.now(),status:'requested'});save();renderAll();showToast('保護者にごほうびを申請したよ 🎁')})}
function navigate(name){document.querySelectorAll('#daughterApp .view').forEach(x=>x.classList.remove('active'));document.querySelector(`#${name}View`).classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===name));if(name==='records')renderRecords();if(name==='rewards')renderRewards();if(name==='graph')renderGraph();scrollTo({top:0,behavior:'smooth'})}
function ask(title,text,action){pendingAction=action;document.querySelector('#confirmTitle').textContent=title;document.querySelector('#confirmText').textContent=text;document.querySelector('#confirmDialog').showModal()}
function showToast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function celebrate(){document.body.animate([{filter:'brightness(1)'},{filter:'brightness(1.08)'},{filter:'brightness(1)'}],{duration:800});showToast('ミッション完了ボーナス +3pt！ ✨')}
function displayDate(key){const d=new Date(key+'T00:00:00');return `${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日（${'日月火水木金土'[d.getDay()]}）`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderHeader(){const h=new Date().getHours();document.querySelector('#greeting').textContent=`${h<11?'おはよう':h<17?'こんにちは':'こんばんは'}、${state.name}！`;document.querySelector('#todayDate').textContent=displayDate(todayKey())}
function renderAll(){renderHeader();renderHome();renderRecords();renderRewards();renderGraph();renderParent();applyMode()}
function applyMode(){document.querySelector('#daughterApp').classList.toggle('hidden',deviceMode==='parent');document.querySelector('#parentApp').classList.toggle('hidden',deviceMode!=='parent')}
function setSyncStatus(text){document.querySelector('#parentSyncStatus').textContent=text;document.querySelector('#connectionLabel').textContent=text}
function chooseMode(){const dialog=document.querySelector('#modeDialog');dialog.showModal();dialog.addEventListener('close',()=>{if(['daughter','parent'].includes(dialog.returnValue)){deviceMode=dialog.returnValue;localStorage.setItem(MODE_KEY,deviceMode);applyMode();renderAll()}else if(!deviceMode)setTimeout(chooseMode,100)},{once:true})}
function startApp(){if(appStarted)return;appStarted=true;normalize();renderAll();if(activeTimer)startTicker();if(!deviceMode)chooseMode();document.querySelector('#authScreen').classList.add('hidden')}
async function handleAuthenticated(user){cloudReady=true;setSyncStatus('クラウドに接続しています…');const remote=await window.AKARI_CLOUD.read().catch(()=>null),migrationKey=`akari-cloud-migrated-${user.uid}`;if(!localStorage.getItem(migrationKey)){state=mergeForMigration(remote,state);normalize();try{await window.AKARI_CLOUD.write(snapshot());localStorage.setItem(migrationKey,'1');cloudConnected=true;showToast('この端末の記録をクラウドへ移行しました')}catch{cloudConnected=false}}else if(remote){state={...initialState(),...remote};normalize();cloudConnected=true}else{normalize();try{await window.AKARI_CLOUD.write(snapshot());cloudConnected=true}catch{cloudConnected=false}}window.AKARI_CLOUD.subscribe((payload,meta)=>{cloudConnected=!meta.fromCache;setSyncStatus(meta.fromCache?'オフライン・保存済み':'クラウドと同期済み');if(!payload||meta.pending)return;if((payload.revision||0)<(state.revision||0))return;state={...initialState(),...payload};normalize();renderAll();if(activeTimer)startTicker()});startApp();setSyncStatus(cloudConnected?'クラウドと同期済み':'オフライン・端末に保存済み');document.querySelector('#accountLabel').textContent=user.email}
function showAuth(){document.querySelector('#authScreen').classList.remove('hidden');document.querySelector('#daughterApp').classList.add('hidden');document.querySelector('#parentApp').classList.add('hidden')}
function authMessage(error){const map={'auth/invalid-credential':'メールアドレスまたはパスワードが違います。','auth/email-already-in-use':'このメールアドレスは登録済みです。「ログイン」を押してください。','auth/weak-password':'パスワードは6文字以上にしてください。','auth/invalid-email':'メールアドレスを確認してください。'};return map[error.code]||'接続できませんでした。通信状態を確認してください。'}
async function submitAuth(register=false){const email=document.querySelector('#emailInput').value.trim(),password=document.querySelector('#passwordInput').value,error=document.querySelector('#authError');error.textContent='';if(!email||password.length<6){error.textContent='メールアドレスと6文字以上のパスワードを入力してください。';return}try{if(register){if(!confirm('このメールアドレスで家族アカウントを作りますか？'))return;await window.AKARI_CLOUD.register(email,password)}else await window.AKARI_CLOUD.login(email,password)}catch(e){error.textContent=authMessage(e)}}
function cloudBoot(){window.AKARI_CLOUD.ready.then(user=>user?handleAuthenticated({uid:user.uid,email:user.email}):showAuth())}

document.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action){const {action:a,id}=action.dataset;if(a==='start')startTimer(id);if(a==='pause')pauseTimer(id);if(a==='finish')toggleComplete(id)}const nav=e.target.closest('[data-nav]');if(nav)navigate(nav.dataset.nav);const reward=e.target.closest('[data-reward]');if(reward&&!reward.disabled)exchange(reward.dataset.name,Number(reward.dataset.reward))});
document.querySelector('#authForm').addEventListener('submit',e=>{e.preventDefault();submitAuth(false)});document.querySelector('#createAccountButton').addEventListener('click',()=>submitAuth(true));
function openSettings(){renderSettings();document.querySelector('#settingsDialog').showModal()}document.querySelector('#settingsButton').addEventListener('click',openSettings);document.querySelector('#parentSettingsButton').addEventListener('click',openSettings);document.querySelector('#saveSettings').addEventListener('click',saveSettings);document.querySelector('#switchModeButton').addEventListener('click',()=>{document.querySelector('#settingsDialog').close();deviceMode=null;localStorage.removeItem(MODE_KEY);chooseMode()});document.querySelector('#logoutButton').addEventListener('click',async()=>{document.querySelector('#settingsDialog').close();await window.AKARI_CLOUD.logout();location.reload()});document.querySelector('#confirmAction').addEventListener('click',()=>{pendingAction?.();pendingAction=null});document.querySelector('#confirmDialog').addEventListener('close',()=>{if(document.querySelector('#confirmDialog').returnValue==='cancel')pendingAction=null});document.addEventListener('visibilitychange',()=>{if(document.hidden)saveLocal();else renderAll()});window.addEventListener('beforeunload',saveLocal);window.addEventListener('akari-sync-error',()=>setSyncStatus('オフライン・端末に保存済み'));window.addEventListener('akari-auth',e=>{if(e.detail.user&&!appStarted)handleAuthenticated(e.detail.user)});
if(window.AKARI_CLOUD)cloudBoot();else window.addEventListener('akari-cloud-ready',cloudBoot,{once:true});
setTimeout(()=>{if(!appStarted&&!window.AKARI_CLOUD){showAuth();document.querySelector('#authError').textContent='クラウド接続を読み込めませんでした。通信状態を確認して、ページを再読み込みしてください。'}},8000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
